### ISSUE TITLE
"electron-forge start " successfully. but error with "electron-forge make"

### ISSUE THREAD

**Issue by wenjun-he** [zarathucorp/shiny-electron-template-m1-2023#6]
When I do the "electron-forge make", the error is following. But, "electron-forge start " successfully.

An unhandled rejection has occurred inside Forge:
RequestError: connect ETIMEDOUT 20.205.243.166:443
at ClientRequest.<anonymous> (/usr/local/lib/node_modules/@electron-forge/cli/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.emit (node:domain:489:12)
    at origin.emit (/usr/local/lib/node_modules/@electron-forge/cli/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)

**Comment by jhk0530** [comment]
Hi, try [this solution](https://github.com/zarathucorp/shiny-electron-template-m1-2023/issues/5#issuecomment-1722477475)

**Comment by wenjun-he** [comment]
It seems a network issue.  Thank you
